name: Upload Userscript Release Assets

on:
  release:
    types:
      - published
      - edited

jobs:
  upload:
    name: Attach userscript assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Upload userscript files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            MxM-Formatter.user.js
            MxM-Formatter.meta.js
          fail_on_unmatched_files: true
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
